version: '3'
services:
  postgres:
    container_name: postgres_container
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "1234"
      POSTGRES_USER: "postgres"         # 선택 사항 (기본값은 postgres)
      POSTGRES_DB: "delivery"

  web:
    container_name: delivery-container
    image: kmsjkh12/delivery
    expose:
      - 8088
    ports:
      - 8088:8088
    depends_on:
      - postgres



